### ISSUE TITLE
cloudflaire 

### ISSUE THREAD

**Issue by faikuluturk** [Kale-Network/kale-blockchain#11]
Stop cloudflair ddos protection we try to run timelord but it claims that ddos atact and doesnt doesnt accept our shares

**Comment by kaleseed** [comment]
Thank you for running timelord. The cloudflair ddos and firewall have been off. Could this be my server setting issue?

**Comment by kaleseed** [comment]
My own timelord stop working also every 10-20 mins... no idea why.

**Comment by kaleseed** [comment]
The chain is generating now. You are welcome to run TL for Kale.
