### ISSUE TITLE
Not Synced

### ISSUE THREAD

**Issue by reall4uk** [Kale-Network/kale-blockchain#14]
Windows is Not Synced
![image](https://user-images.githubusercontent.com/36640994/125201584-7c0b4b80-e278-11eb-9bba-41dfbd114ff5.png)

**Comment by kaleseed** [comment]
now has been 10+PB space, have you synced? I can share some full nodes with you if necessary.

**Comment by ngochoangf** [comment]
> now has been 10+PB space, have you synced? I can share some full nodes with you if necessary.

share me ip full node plz

**Comment by reall4uk** [comment]
> now has been 10+PB space, have you synced? I can share some full nodes with you if necessary.

Yes, I synced!  had to remove .kale.  It's a shame that the launch was waiting most of all, and so late I was able to log in due to an error.. Now it is much more difficult to extract

**Comment by kaleseed** [comment]
@ngochoangf  
<html>
<body>


Full node | node-1.kalenetwork.org | 6333
-- | -- | --
Full node | node-2.kalenetwork.org | 6333
Full node | node-3.kalenetwork.org | 6333


</body>
</html>

**Comment by kaleseed** [comment]
@reall4uk sorry for the delay and some previous issues. Glad to know that you are synced.
