### ISSUE TITLE
Strange windows cli issue

### ISSUE THREAD

**Issue by inan0812** [Kale-Network/kale-blockchain#20]
When running kale from a windows powershell cli, after running "kale.exe start farmer" ->

I start getting what appears to be info level linux timelord logs output to stdout. I am not running any timelords on this system.

Not sure if this is network side or client side issue.

Anyone else experiencing this issue?

I'm farming like 8 other forks this way, but this does not happen on any of the other windows.

**Comment by kaleseed** [comment]
The log is set to INFO level by default, you can change that level in the config.yaml. If the TL is not set to run, it should not start. Could you elaborate on what kinds of TL logs? I can try to reproduce this.

**Comment by inan0812** [comment]
> The log is set to INFO level by default, you can change that level in the config.yaml. If the TL is not set to run, it should not start. Could you elaborate on what kinds of TL logs? I can try to reproduce this.

I'm not running a Timelord. I'm getting someone else's timelord lord coming through in my cli window, where there is normally no output.

Windows timelords don't produce VDF logs, which is what I'm seeing.

**Comment by kaleseed** [comment]
Interesting... I tried to reproduce this issue without success. Will keep watching the log file anything about the timelord.

**Comment by inan0812** [comment]
I deleted my mainnet folder and reinstalled. The issue went away. No idea why it happened in the first place.
