### ISSUE TITLE
Won't sync [BUG]

### ISSUE THREAD

**Issue by gntz555** [Kale-Network/kale-blockchain#22]
Won't sync after very first installation.

Maybe it's conflicting ports?

Also even with manually put peers (intoducer and full nodes), it doesn't work. They can't/ won't even be added.

**Comment by panDon** [comment]
me too.......

**Comment by kaleseed** [comment]
did you install the Kale before 0.1.18? Please delete the .kale folder in the current user account. will sync smoothly.

**Comment by kaleseed** [comment]
Here are some nodes, in case you need them: 
109.201.176.14:6333
147.158.164.226:6333
152.228.250.218:6333
76.28.37.174:6333
84.19.66.51:6333

**Comment by kaleseed** [comment]
close this issue now, if the issue persists, please feel free to reopen it.

**Comment by gntz555** [comment]
I installed the newest version ant also for the very first time.

**Comment by gntz555** [comment]
> Here are some nodes, in case you need them:
> 109.201.176.14:6333
> 147.158.164.226:6333
> 152.228.250.218:6333
> 76.28.37.174:6333
> 84.19.66.51:6333

I closed everything related to chia and just opened kale and added some of the nodes of this list. Now it is actually syncing for the very first time. Thank you very much!

The introducer or official nodes however, don't show up in the list after I tried to add those. Is it shown like 
"node-1.kalenetwork.org" for you?
