### ISSUE TITLE
Sync Issue, stuck on 0

### ISSUE THREAD

**Issue by kaanninka** [Kale-Network/kale-blockchain#25]
my sync never increases, even clean reinstall 0.1.180, any solution?
all 8 nodes and more on height 14.456

![image](https://user-images.githubusercontent.com/86846372/125537399-2d589e2b-a192-48d9-84c1-19ea2ae058a5.png)

**Comment by kaleseed** [comment]
did you delete the **.kale** folder in the current user?

**Comment by sergiosurvival** [comment]
no carga se queda signed en rojo sincronizando

**Comment by sergiosurvival** [comment]
![2021-07-14](https://user-images.githubusercontent.com/83919237/125617722-d1a58623-bb01-42e5-a7c4-c5221daf2c59.png)

**Comment by kaleseed** [comment]
close this issue, but feel free to reopen.
