### ISSUE TITLE
Difficulty constant too low

### ISSUE THREAD

**Issue by inan0812** [Kale-Network/kale-blockchain#3]
This chain will break as soon as it's discovered by chia fork farmers due to the 2^57 difficulty constant. I recommend changing it to 2^68.

**Comment by kaleseed** [comment]
Thank you for the insightful suggestion, will do it.

**Comment by inan0812** [comment]
starting difficulty of 50 might be a bit much for 2^68... It will even out, but thats a lot.

**Comment by reall4uk** [comment]
send me NODE please

**Comment by inan0812** [comment]
> send me NODE please

There is no introducer or timelord AFAIK. So the chain doesn't appear to have started. I have no idea.

**Comment by vanthoi** [comment]
> This chain will break as soon as it's discovered by chia fork farmers due to the 2^57 difficulty constant. I recommend changing it to 2^68.

k32 like 2^67 from chia!

**Comment by kaleseed** [comment]
These difficulty parameters are tricky... thank you guys for sharing.
