### ISSUE TITLE
Please give me a node

### ISSUE THREAD

**Issue by 1617176084** [Kale-Network/kale-blockchain#5]

**Comment by marcelo74mayo** [comment]
need some nodes

**Comment by reall4uk** [comment]
NOdes please

**Comment by reall4uk** [comment]
send node for me please from mail real_t89@mail.ru

**Comment by 1617176084** [comment]
send node for me please from mail 1617176084@qq.com

**Comment by juantesho** [comment]
si tienen pasen nodo por favor. muchas gracias

**Comment by david306** [comment]
send node for me please from mail ledav206@gmail.com

**Comment by nmkyuppie** [comment]
Did anyone get a node?

**Comment by nowing11** [comment]
Me Too Krissada_2004@hotmail.com

**Comment by Adlan2003** [comment]
send node for me please from mail adhadashev@gmail.com

**Comment by kaleseed** [comment]
45.149.112.230:6333

**Comment by Adlan2003** [comment]
> 45.149.112.230:6333

![image](https://user-images.githubusercontent.com/85718536/125179200-d1057e00-e1f4-11eb-8109-f39b9fc52814.png)
Doesn't want to connect
